# Build stage
FROM node:20 AS build
WORKDIR /app
COPY client/package*.json ./
RUN npm install
COPY client/ .
# EXPOSE 63686
# CMD ["npm", "run", "dev"]

# Builds the project without TS checks.
RUN npm run safeBuild

# Production stage (serve static files with nginx)
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]